config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  get "/about", to: "home#about"

  resources :books, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = [
      {id: 1, name: 'Libro 1', author: 'Autor 1'},
      {id: nil, name: 'Libro 2', author: 'Autor 2'},
      {id: 3, name: 'Libro 3', author: 'Autor 3'},
    ]
  end

  def show
    @books = [
      {id: 1, name: 'Libro 1', author: 'Autor 1'},
      {id: nil, name: 'Libro 2', author: 'Autor 2'},
      {id: 3, name: 'Libro 3', author: 'Autor 3'},
    ]

    @book = @books.select { |book| book[:id].to_s == params[:id] }.first
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
Author: <%= book[:author] %> | Book Name: <%= book[:name] %> | <%= link_to "Go to book's page", book_path(book[:id]) %>

app/views/books/index.html.erb
<h1>Books</h1>

<% @books.each do |book|%>
  <% unless book[:id].nil? %>
    <p><%= render partial: 'book', locals: { :book => book } %></p>
  <% end %>
<% end %>

app/views/books/show.html.erb
<h1>Book <%= @book[:id] %></h1>

<p><%= render partial: 'book', locals: { :book => @book } %></p>

app/views/home/about.html.erb
<h1>About</h1>
<h3>Phone Number: (123) 456 7890</h3>
<h3>Email: support@booksonline.com</h3>

app/views/home/index.html.erb
<h1>Welcome to the site</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiPrimerAppEnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= link_to 'Logo', root_path %> | <%= link_to 'Books', books_path %> | <%= link_to 'About', about_path %>
    </header>
    <main><%= yield %></main>
    <footer>
      Copyright &copy; <%= Time.zone.now.year %>
    </footer>
  </body>
</html>